import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/header/layout";
import Navbar from "./components/Navbar/layout";
import StyledComponentsRegistry from "@/registry";
import Footer from "./components/Footer/layout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <StyledComponentsRegistry>
          <Header/>
          <Navbar/>
          {children}
          <Footer/>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
